export const ActionType = {
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    DEC_ITEM_IN_CART:"DEC_ITEM_IN_CART",
    FETCH_MY_ORDER:"FETCH_MY_ORDER",
    FETCH_MY_ORDER_DETAILS:"FETCH_MY_ORDER_DETAILS",
    REMOVE_FETCH_MY_ORDER_DETAILS:"REMOVE_FETCH_MY_ORDER_DETAILS",
    SET_ALL_VARIANTS:"SET_ALL_VARIANTS",
    RESET_ALL_VARIANTS:"RESET_ALL_VARIANTS"
}